---
driver_plugin: openstack
driver_config:
  name: openstack
  openstack_username: "<%= ENV['KITCHEN_OS_USERNAME'] %>"
  openstack_api_key: "<%= ENV['KITCHEN_OS_PASSWORD'] %>"
  openstack_auth_url: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_identity_endpoint: "<%= ENV['KITCHEN_OS_AUTH_URL'] %>"
  openstack_tenant: "<%= ENV['KITCHEN_OS_TENANT_NAME'] %>"
  key_name: "<%= ENV['KITCHEN_OS_KEY_NAME'] %>"
  private_key_path: "<%= ENV['PWD'] %>/.kitchen.key"
  floating_ip_pool: "<%= ENV['KITCHEN_OS_FLOATING_IP_POOL'] %>"
  flavor_ref: "<%= ENV['KITCHEN_OS_FLV_1_vCPU_RAM_2G'] %>"
  username: stack


platforms:
  - name: debian-7.0
    driver_config:
      image_ref: <%= ENV['KITCHEN_OS_IMG_DEBIAN7'] %>

suites:
- name: stumpwm
  run_list:
  - recipe[stumpwm]
  - recipe[stumpwm::xsession]
  attributes: {
    stumpwm: {
      build_dir: "/opt/stumpwm",
      quicklisp_dir: "/opt/quicklisp"
    }
  }
