---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: debian-7.6
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[git]
      - recipe[stumpwm]
      - recipe[stumpwm::xsession]
    attributes:
      stumpwm:
        build_dir: /opt/stumpwm
        quicklisp_dir: /opt/quicklisp
        user: kitchen
